### ISSUE TITLE
Add user API

### ISSUE THREAD

**Issue by kiranparajuli589** [kiranparajuli589/ESALE#15]
## Description
- Need to write strong api backend for user authentication/manipulation

## Motivation
- #5 
- #7 

## TODO:
- [x] Add user/s  #14 https://github.com/kiranparajuli589/ESALE/pull/29/commits/359a79857ba1ed4fb24b6958e921f20d9e52d04e
- [x] Retrieve user/s https://github.com/kiranparajuli589/ESALE/pull/29/commits/359a79857ba1ed4fb24b6958e921f20d9e52d04e
- [x] Edit user/s https://github.com/kiranparajuli589/ESALE/pull/29/commits/359a79857ba1ed4fb24b6958e921f20d9e52d04e
- [x] Delete user/s https://github.com/kiranparajuli589/ESALE/pull/29/commits/359a79857ba1ed4fb24b6958e921f20d9e52d04e

**Comment by kiranparajuli589** [comment]
Done!
