### ISSUE TITLE
Setup favorable test framework for python backend

### ISSUE THREAD

**Issue by kiranparajuli589** [kiranparajuli589/ESALE#20]
**Is your feature request related to a problem? Please describe.**
Currently we do not use any sort of testing framework to check our APIs. It is always a good idea to setup a testing framework so that you can track bugs or issues whenever there is a change in feature, code-changes...

**Describe the solution you'd like**
Testing framework with following characteristics should be implemented
- easy to setup and write tests
- maintainable
- python programming language
- BDD, automated tests

**Describe alternatives you've considered**
- _**Behave**_ is a behavior driven development, python style.
- _Behavior-driven development_ (or **BDD**) is an agile software development technique that encourages collaboration between developers, QA and non-technical or business participants in a software project.
- `Behave` uses tests written in a natural language style, backed up by Python code.

**Additional context**

**Comment by kiranparajuli589** [comment]
Issue resolved by #22 
closing this!

**Comment by kiranparajuli589** [comment]
# behave django

## Description:
Behave BDD integration for Django

## Features:
- Web Browser Automation ready
- Database transactions per scenario
- Use Django's testing client
- Use unittest + Django assert library
- Use behave's command line arguments
- Use behave's configuration file
- Fixture loading

** Behave is a powerful testing framework for python apps, but when we are working with django, we can be move bounded with behave using behave-django ** 

## Todo
- [ ] Setup behave-django environment
- [ ] Add test scenarios
- [ ] Add acceptance tests for **APIs** as well as **webUI**

**Comment by kiranparajuli589** [comment]
Alas! `behave` & `behave-django` is not what we need
We can perform testing inside DRF with integrated tests with `APIClient`
Closing Due to #35
