### ISSUE TITLE
[ESALE2.0] Lightening before the thunder

### ISSUE THREAD

**Issue by kiranparajuli589** [kiranparajuli589/ESALE#30]
## Description
This is a great approach....From now on, make changes for backend on this branch only using PR's
otherwise it would be tough to manage changes flow

**TODO:**
- [ ] Make working login, logout, users & profile APIs
- [ ] Setup cors
- [ ] Login, Logout & Dashboard Pages on Eclipse
- [ ] Integration of Vue with RestAPIs
- [ ] Setup behave for apiTests
