### ISSUE TITLE
Why VueJs Frontend

### ISSUE THREAD

**Issue by kiranparajuli589** [kiranparajuli589/ESALE#9]
## Description
- **Vue.js** (commonly referred to as Vue; pronounced /vjuː/, like "view") is an open-source Model–view–viewmodel JavaScript framework for building user interfaces and single-page applications.
- **Vue** is easy to pick up and integrate with other libraries or existing projects, but can scale up to power sophisticated web applications.

## Motivation
- See #5 

## Related Issues
- Part of #8

## ToDo
- [x] VueJs Setup #10
- [x] Vue-Django Connection #10 
- [ ] Create Auth Frontend
- [ ] Create ESALE Frontend
## How Has This Been Tested?

- :robot:

## Types of changes
- [x] New feature

## Checklist:
- [x] Code changes
- [ ] Unit tests added
- [ ] Acceptance tests added
